const fs = require('fs');
let content = fs.readFileSync('src/components/SchoolApp.jsx', 'utf8');

const printFn = `
  const printStudentReport = (s) => {
    const today = new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' });
    const clsName = classes.find(c => c.id === s.classId)?.name || '-';
    const att = attendance.filter(a => a.studentId === s.id);
    const present = att.filter(a => a.status === 'Present').length;
    const absent  = att.filter(a => a.status === 'Absent').length;
    const late    = att.filter(a => a.status === 'Late').length;
    const excused = att.filter(a => a.status === 'Excused').length;
    const total   = att.length;
    const pct     = total ? Math.round(present / total * 100) : 0;
    const win = window.open('', '_blank');
    const html = '<!DOCTYPE html><html><head><title>Student Report - ' + s.name + '</title>'
      + '<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:Times New Roman,serif;color:#1a1a1a;padding:60px;max-width:800px;margin:0 auto}.header{display:flex;align-items:center;border-bottom:3px solid #0d9488;padding-bottom:16px;margin-bottom:30px}.logo{width:70px;height:70px;object-fit:contain;margin-right:20px}.school-center{flex:1;text-align:center}.school-name{font-size:22px;font-weight:bold;color:#0d9488}.school-sub{font-size:12px;color:#64748b;margin-top:3px}p{font-size:14px;line-height:1.9;margin-bottom:14px}h2{font-size:14px;font-weight:bold;color:#0d9488;margin:20px 0 8px}table{width:100%;border-collapse:collapse;margin:8px 0}td,th{padding:9px 14px;border:1px solid #d1d5db;font-size:13px}td:first-child{background:#f9fafb;font-weight:bold;width:38%}th{background:#f1f5f9;font-weight:600;text-align:left}.sig-line{border-top:1px solid #1a1a1a;width:200px;margin-top:48px;margin-bottom:6px}.footer{margin-top:40px;padding-top:12px;border-top:1px solid #e5e7eb;text-align:center;font-size:11px;color:#9ca3af}@media print{button{display:none!important}}</style></head><body>'
      + '<div class="header"><img src="/logo.png" class="logo" onerror="this.style.display=\'none\'" /><div class="school-center"><div class="school-name">Al-Huffath Academy</div><div class="school-sub">Ilm | Iman | Hifz</div><div class="school-sub">admin@al-huffath.edu</div></div></div>'
      + '<p style="margin-bottom:24px">' + today + '</p>'
      + '<p><b>To Whom It May Concern,</b></p>'
      + '<p style="font-weight:bold;border-bottom:2px solid #1a1a1a;padding-bottom:6px;margin-bottom:24px;text-transform:uppercase;letter-spacing:1px">OBJECT: <span style="font-weight:normal">Student Academic Report</span></p>'
      + '<p>This report is issued by Al-Huffath Academy to provide an official summary of the academic record of the student detailed below:</p>'
      + '<h2>Student Information</h2><table>'
      + '<tr><td>Full Name</td><td>' + s.name + '</td></tr>'
      + '<tr><td>Student ID</td><td>' + s.sid + '</td></tr>'
      + '<tr><td>Class</td><td>' + clsName + '</td></tr>'
      + '<tr><td>Gender</td><td>' + (s.gender||'-') + '</td></tr>'
      + '<tr><td>Phone</td><td>' + (s.phone||'-') + '</td></tr>'
      + '<tr><td>Status</td><td>' + s.status + '</td></tr>'
      + '<tr><td>Report Issued On</td><td>' + today + '</td></tr>'
      + '</table>'
      + '<h2>Attendance Summary</h2><table>'
      + '<tr><td>Present</td><td>' + present + ' days</td></tr>'
      + '<tr><td>Absent</td><td>' + absent + ' days</td></tr>'
      + '<tr><td>Late</td><td>' + late + ' days</td></tr>'
      + '<tr><td>Excused</td><td>' + excused + ' days</td></tr>'
      + '<tr><td>Attendance Rate</td><td><b>' + pct + '%</b></td></tr>'
      + '</table>'
      + '<p style="margin-top:20px">This report is provided upon request for administrative and verification purposes.</p>'
      + '<div style="margin-top:50px"><p>Regards,</p><div class="sig-line"></div><p style="font-weight:bold;font-size:13px">School Principal</p><p style="font-size:12px;color:#64748b">Al-Huffath Academy</p></div>'
      + '<div style="margin-top:28px"><button onclick="window.print()" style="padding:10px 28px;background:#0d9488;color:#fff;border:none;border-radius:6px;font-size:14px;cursor:pointer">Print Report</button></div>'
      + '<div class="footer">Generated by EduManage | Developed by Eng. Ahmad Zouikli | ' + today + '</div>'
      + '</body></html>';
    win.document.write(html);
    win.document.close();
  };
`;

content = content.replace('  const toggleAll = ()', printFn + '  const toggleAll = ()');

const oldBtn = '>Delete</button>\n                      </div>';
const newBtn = '>Delete</button>\n                        <button onClick={() => printStudentReport(s)} style={{ padding: "5px 12px", borderRadius: 6, border: "none", background: "#d1fae5", fontSize: 12, cursor: "pointer", color: "#065f46" }}>Report</button>\n                      </div>';
content = content.replace(oldBtn, newBtn);

fs.writeFileSync('src/components/SchoolApp.jsx', content, 'utf8');
console.log('Done!');
