const fs = require('fs');
let content = fs.readFileSync('src/components/SchoolApp.jsx', 'utf8');

const oldPanel = "        {compose ? (\r\n          /* Compose Panel */";
const newPanel = "        {broadcast ? (\r\n          /* Broadcast Panel */\r\n          <div style={{ flex: 1, padding: 28, overflowY: \"auto\" }}>\r\n            <div style={{ fontSize: 16, fontWeight: 700, color: \"#7c3aed\", marginBottom: 20 }}>📢 Broadcast Message</div>\r\n            <Field label=\"Send To\">\r\n              <select value={bcForm.classId} onChange={e => setBcForm({...bcForm, classId: e.target.value})} style={selectStyle}>\r\n                <option value=\"all\">📚 All Students</option>\r\n                {classes.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}\r\n              </select>\r\n            </Field>\r\n            <Field label=\"Subject\">\r\n              <input value={bcForm.subject} onChange={e => setBcForm({...bcForm, subject: e.target.value})} placeholder=\"Message subject...\" style={inputStyle} />\r\n            </Field>\r\n            <Field label=\"Message\">\r\n              <textarea value={bcForm.body} onChange={e => setBcForm({...bcForm, body: e.target.value})} placeholder=\"Write your message...\" rows={6} style={{...inputStyle, resize: \"vertical\"}} />\r\n            </Field>\r\n            <div style={{ display: \"flex\", gap: 10, marginTop: 8 }}>\r\n              <button onClick={sendBroadcast} style={{ flex: 1, padding: \"11px\", borderRadius: 9, border: \"none\", background: \"#7c3aed\", color: \"#fff\", fontSize: 14, fontWeight: 600, cursor: \"pointer\", fontFamily: \"inherit\" }}>\r\n                📢 Send to {bcForm.classId === \"all\" ? \"All Students\" : classes.find(c=>c.id===parseInt(bcForm.classId))?.name || \"Class\"}\r\n              </button>\r\n              <button onClick={() => setBroadcast(false)} style={{ padding: \"11px 20px\", borderRadius: 9, border: `1px solid ${T.border}`, background: \"#fff\", fontSize: 14, cursor: \"pointer\", fontFamily: \"inherit\" }}>Cancel</button>\r\n            </div>\r\n          </div>\r\n        ) : compose ? (\r\n          /* Compose Panel */";

if (content.includes(oldPanel)) {
  content = content.replace(oldPanel, newPanel);
  console.log('Broadcast UI added!');
} else { console.log('ERROR: not found!'); }

fs.writeFileSync('src/components/SchoolApp.jsx', content, 'utf8');