# -*- coding: utf-8 -*-
content = open('src/components/SchoolApp.jsx', encoding='utf-8').read()

old_report = '''                      const win = window.open("", "_blank");
                      win.document.write(
                        "<html><head><title>Teacher Report</title>" +
                        "<style>body{font-family:Arial;padding:30px;color:#1e1e3a}h1{color:#0d9488;border-bottom:2px solid #0d9488;padding-bottom:8px}table{width:100%;border-collapse:collapse;margin-top:16px}td,th{border:1px solid #e2e8f0;padding:10px 14px;text-align:left}th{background:#f1f5f9;font-weight:600;width:40%}@media print{button{display:none}}</style>" +
                        "</head><body>" +
                        "<h1>Teacher Report</h1>" +
                        "<table>" +
                        "<tr><th>Full Name</th><td>" + teacher.name + "</td></tr>" +
                        "<tr><th>Subject</th><td>" + (teacher.subject || "-") + "</td></tr>" +
                        "<tr><th>Email</th><td>" + (teacher.email || "-") + "</td></tr>" +
                        "<tr><th>Phone</th><td>" + (teacher.phone || "-") + "</td></tr>" +
                        "<tr><th>Status</th><td>" + (teacher.status || "-") + "</td></tr>" +
                        "<tr><th>Start Date</th><td>" + startDate + "</td></tr>" +
                        "<tr><th>Assigned Classes</th><td>" + clsNames + "</td></tr>" +
                        "<tr><th>Report Date</th><td>" + today + "</td></tr>" +
                        "</table>" +
                        "<br><button onclick='window.print()' style='padding:10px 24px;background:#0d9488;color:#fff;border:none;border-radius:8px;font-size:14px;cursor:pointer'>Print Report</button>" +
                        "<p style='margin-top:40px;font-size:11px;color:#94a3b8;text-align:center'>Generated by EduManage | Developed by Eng. Ahmad Zouikli | " + today + "</p>" +
                        "</body></html>"
                      );
                      win.document.close();'''

new_report = '''                      const win = window.open("", "_blank");
                      win.document.write(
                        "<html><head><title>Teacher Report - " + teacher.name + "</title>" +
                        "<style>" +
                        "* { box-sizing: border-box; margin: 0; padding: 0; }" +
                        "body { font-family: 'Times New Roman', serif; color: #1a1a1a; background: #fff; padding: 60px; max-width: 800px; margin: 0 auto; }" +
                        ".header { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #0d9488; padding-bottom: 20px; margin-bottom: 30px; }" +
                        ".school-info { text-align: right; }" +
                        ".school-name { font-size: 22px; font-weight: bold; color: #0d9488; }" +
                        ".school-sub { font-size: 13px; color: #64748b; margin-top: 4px; }" +
                        ".logo { width: 80px; height: 80px; object-fit: contain; }" +
                        ".date-block { text-align: right; margin-bottom: 30px; font-size: 14px; color: #374151; }" +
                        ".to-block { margin-bottom: 24px; font-size: 14px; }" +
                        ".subject-line { font-size: 15px; font-weight: bold; border-bottom: 2px solid #1a1a1a; padding-bottom: 6px; margin-bottom: 28px; text-transform: uppercase; letter-spacing: 1px; }" +
                        ".body-text { font-size: 14px; line-height: 2; color: #1a1a1a; margin-bottom: 16px; }" +
                        ".info-table { width: 100%; border-collapse: collapse; margin: 20px 0; }" +
                        ".info-table td { padding: 10px 16px; border: 1px solid #d1d5db; font-size: 14px; }" +
                        ".info-table td:first-child { background: #f9fafb; font-weight: bold; width: 40%; }" +
                        ".signature-block { margin-top: 60px; }" +
                        ".sig-line { border-top: 1px solid #1a1a1a; width: 200px; margin-top: 50px; }" +
                        ".sig-name { font-size: 13px; margin-top: 6px; font-weight: bold; }" +
                        ".sig-title { font-size: 12px; color: #64748b; }" +
                        ".footer { margin-top: 50px; padding-top: 16px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 11px; color: #9ca3af; }" +
                        "@media print { button { display: none !important; } body { padding: 40px; } }" +
                        "</style></head><body>" +
                        "<div class='header'>" +
                        "<img src='/logo.png' class='logo' onerror=\"this.style.display='none'\" />" +
                        "<div class='school-info'>" +
                        "<div class='school-name'>Al-Huffath Academy</div>" +
                        "<div class='school-sub'>Ilm | Iman | Hifz</div>" +
                        "<div class='school-sub' style='margin-top:2px;font-size:11px'>admin@al-huffath.edu</div>" +
                        "</div>" +
                        "</div>" +
                        "<div class='date-block'>" + today + "</div>" +
                        "<div class='to-block'><b>To Whom It May Concern,</b></div>" +
                        "<div class='subject-line'>OBJECT: Confirmation of Employment & Teaching Record</div>" +
                        "<p class='body-text'>This letter is issued by Al-Huffath Academy administration to confirm the employment and teaching record of the staff member detailed below:</p>" +
                        "<table class='info-table'>" +
                        "<tr><td>Full Name</td><td>" + teacher.name + "</td></tr>" +
                        "<tr><td>Subject Taught</td><td>" + (teacher.subject || "-") + "</td></tr>" +
                        "<tr><td>Assigned Classes</td><td>" + clsNames + "</td></tr>" +
                        "<tr><td>Email Address</td><td>" + (teacher.email || "-") + "</td></tr>" +
                        "<tr><td>Phone Number</td><td>" + (teacher.phone || "-") + "</td></tr>" +
                        "<tr><td>Employment Status</td><td>" + (teacher.status || "-") + "</td></tr>" +
                        "<tr><td>Start Date</td><td>" + startDate + "</td></tr>" +
                        "<tr><td>Report Issued On</td><td>" + today + "</td></tr>" +
                        "</table>" +
                        "<p class='body-text'>This confirmation is provided upon request for administrative and verification purposes.</p>" +
                        "<p class='body-text'>If you require any additional information, please contact the school administration.</p>" +
                        "<div class='signature-block'>" +
                        "<p style='font-size:14px'>Regards,</p>" +
                        "<div class='sig-line'></div>" +
                        "<div class='sig-name'>School Principal</div>" +
                        "<div class='sig-title'>Al-Huffath Academy</div>" +
                        "</div>" +
                        "<div style='margin-top:30px'><button onclick='window.print()' style='padding:10px 28px;background:#0d9488;color:#fff;border:none;border-radius:6px;font-size:14px;cursor:pointer;font-family:inherit'>Print Letter</button></div>" +
                        "<div class='footer'>Generated by EduManage &nbsp;|&nbsp; Developed by Eng. Ahmad Zouikli &nbsp;|&nbsp; " + today + "</div>" +
                        "</body></html>"
                      );
                      win.document.close();'''

if old_report in content:
    content = content.replace(old_report, new_report)
    print('Report design updated!')
else:
    print('ERROR: not found!')

open('src/components/SchoolApp.jsx', 'w', encoding='utf-8').write(content)
print('Done!')
