const fs = require('fs');
let content = fs.readFileSync('src/components/SchoolApp.jsx', 'utf8');

const oldForm = "            <select name=\"status\" defaultValue={editing?.status || \"active\"} className=\"w-full p-2 border rounded mb-4\">\r\n              <option value=\"active\">Active</option>\r\n              <option value=\"inactive\">Inactive</option>\r\n            </select>\r\n            <div className=\"flex gap-2\">";

const newForm = "            <select name=\"status\" defaultValue={editing?.status || \"active\"} className=\"w-full p-2 border rounded mb-3\">\r\n              <option value=\"active\">Active</option>\r\n              <option value=\"inactive\">Inactive</option>\r\n            </select>\r\n            <label className=\"block text-sm font-medium text-slate-600 mb-1\">Start Date</label>\r\n            <input name=\"startDate\" type=\"date\" defaultValue={editing?.startDate} className=\"w-full p-2 border rounded mb-3\" />\r\n            {classes.length > 0 && (\r\n              <div className=\"mb-4\">\r\n                <label className=\"block text-sm font-medium text-slate-600 mb-2\">Assigned Classes</label>\r\n                <div className=\"border rounded p-2 max-h-36 overflow-y-auto flex flex-col gap-1\">\r\n                  {classes.map(cls => (\r\n                    <label key={cls.id} className=\"flex items-center gap-2 cursor-pointer text-sm\">\r\n                      <input type=\"checkbox\" name=\"classIds\" value={cls.id}\r\n                        defaultChecked={(editing?.classIds||[]).map(x=>parseInt(x)).includes(cls.id)} />\r\n                      {cls.name}\r\n                    </label>\r\n                  ))}\r\n                </div>\r\n              </div>\r\n            )}\r\n            <div className=\"flex gap-2\">";

if (content.includes(oldForm)) { content = content.replace(oldForm, newForm); console.log('Step 3 fixed!'); }
else { console.log('ERROR step 3'); }

fs.writeFileSync('src/components/SchoolApp.jsx', content, 'utf8');