# -*- coding: utf-8 -*-
content = open('src/components/SchoolApp.jsx', encoding='utf-8').read()

old = '            {/* Tabs */}\n            <div style={{ display: "flex", marginTop: 18 }}>\n              {PROFILE_TABS.map(t => (\n                <button key={t} onClick={() => setTab(t)} style={{\n                  padding: "10px 18px", border: "none", cursor: "pointer", fontFamily: "inherit",\n                  fontSize: 13, fontWeight: 500, background: "transparent",\n                  color: tab === t ? "#fff" : "rgba(255,255,255,.42)",\n                  borderBottom: tab === t ? "2px solid #0d9488" : "2px solid transparent",\n                  transition: "all .15s",\n                }}>{t}</button>\n              ))}\n          '

new = """            {/* Tabs */}
            <div style={{ display: "flex", marginTop: 18, alignItems: "center", justifyContent: "space-between" }}>
              <div style={{ display: "flex" }}>
              {PROFILE_TABS.map(t => (
                <button key={t} onClick={() => setTab(t)} style={{
                  padding: "10px 18px", border: "none", cursor: "pointer", fontFamily: "inherit",
                  fontSize: 13, fontWeight: 500, background: "transparent",
                  color: tab === t ? "#fff" : "rgba(255,255,255,.42)",
                  borderBottom: tab === t ? "2px solid #0d9488" : "2px solid transparent",
                  transition: "all .15s",
                }}>{t}</button>
              ))}
              </div>
              <button onClick={() => {
                const rows = gradeStats.rows.map(r => r.total !== null ? (
                  "<tr><td>" + r.sub.name + "</td><td>" + (r.g.quiz||0) + "/100</td><td>" + (r.g.homework||0) + "/100</td><td>" + (r.g.midterm||0) + "/100</td><td>" + (r.g.final||0) + "/100</td><td><b>" + r.total + "</b></td><td><b>" + r.letter + "</b></td></tr>"
                ) : "").join("");
                const win = window.open("", "_blank");
                win.document.write("<html><head><title>Report - " + student.name + "</title><style>body{font-family:Arial;padding:30px;color:#1e1e3a}h1{color:#0d9488;border-bottom:2px solid #0d9488;padding-bottom:8px}h2{color:#1e1e3a;margin-top:24px}table{width:100%;border-collapse:collapse;margin-top:10px}td,th{border:1px solid #e2e8f0;padding:8px 12px;text-align:left}th{background:#f1f5f9;font-weight:600}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.info-item{background:#f8fafc;padding:10px;border-radius:8px}.info-label{font-size:11px;color:#64748b;font-weight:600}.info-value{font-size:14px;color:#1e1e3a;margin-top:2px}@media print{button{display:none}}</style></head><body>" +
                  "<h1>Student Comprehensive Report</h1>" +
                  "<div class=\\"info-grid\\">" +
                  "<div class=\\"info-item\\"><div class=\\"info-label\\">FULL NAME</div><div class=\\"info-value\\">" + student.name + "</div></div>" +
                  "<div class=\\"info-item\\"><div class=\\"info-label\\">STUDENT ID</div><div class=\\"info-value\\">" + student.sid + "</div></div>" +
                  "<div class=\\"info-item\\"><div class=\\"info-label\\">CLASS</div><div class=\\"info-value\\">" + (cls?.name||"-") + "</div></div>" +
                  "<div class=\\"info-item\\"><div class=\\"info-label\\">GENDER</div><div class=\\"info-value\\">" + student.gender + "</div></div>" +
                  "<div class=\\"info-item\\"><div class=\\"info-label\\">PHONE</div><div class=\\"info-value\\">" + student.phone + "</div></div>" +
                  "<div class=\\"info-item\\"><div class=\\"info-label\\">STATUS</div><div class=\\"info-value\\">" + student.status + "</div></div>" +
                  "</div>" +
                  "<h2>Attendance Summary</h2>" +
                  "<table><tr><th>Present</th><th>Absent</th><th>Late</th><th>Excused</th><th>Total</th><th>Rate</th></tr>" +
                  "<tr><td>" + attStats.present + "</td><td>" + attStats.absent + "</td><td>" + attStats.late + "</td><td>" + attStats.excused + "</td><td>" + attStats.total + "</td><td><b>" + attStats.rate + "%</b></td></tr></table>" +
                  "<h2>Academic Performance (GPA: " + (gradeStats.gpa||"-") + ")</h2>" +
                  "<table><tr><th>Subject</th><th>Quiz</th><th>Homework</th><th>Midterm</th><th>Final</th><th>Total</th><th>Grade</th></tr>" + rows + "</table>" +
                  "<br><button onclick=\\"window.print()\\" style=\\"padding:10px 24px;background:#0d9488;color:#fff;border:none;border-radius:8px;font-size:14px;cursor:pointer\\">Print Report</button>" +
                  "<p style=\\"margin-top:40px;font-size:11px;color:#94a3b8;text-align:center\\">Generated by EduManage | Developed by Eng. Ahmad Zouikli | " + new Date().toLocaleDateString() + "</p>" +
                  "</body></html>");
                win.document.close();
              }} style={{ marginRight: 12, marginBottom: 6, padding: "7px 16px", borderRadius: 8, border: "none", background: "#0d9488", color: "#fff", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
                Print Full Report
              </button>
          """

if old in content:
    content = content.replace(old, new)
    print('Print button added!')
else:
    print('ERROR: pattern not found!')

open('src/components/SchoolApp.jsx', 'w', encoding='utf-8').write(content)
print('Done!')
